# This is a config for E2B sandbox template.
# You can use 'template_id' (k0wmnzir0zuzye6dndlw) or 'template_name (desktop) from this config to spawn a sandbox:

# Python SDK
# from e2b import Sandbox
# sandbox = Sandbox(template='desktop')

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create({ template: 'desktop' })

template_id = "k0wmnzir0zuzye6dndlw"
dockerfile = "e2b.Dockerfile"
template_name = "desktop"
start_cmd = "/start-up.sh"
cpu_count = 4
memory_mb = 4_096
team_id = "460355b3-4f64-48f9-9a16-4442817f79f5"
