# This is a config for E2B sandbox template.
# You can use template ID (22ovhf9tf6z5b43m4wkx) or template name (ubuntu-desktop) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("ubuntu-desktop") # Sync sandbox
# sandbox = await AsyncSandbox.create("ubuntu-desktop") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('ubuntu-desktop')

template_id = "22ovhf9tf6z5b43m4wkx"
dockerfile = "e2b.Dockerfile"
template_name = "ubuntu-desktop"
start_cmd = "/start-up.sh"
cpu_count = 4
memory_mb = 4_096
team_id = "d610ca28-d4db-49e5-b977-86342d8036f2"
